spring.application.name=SpringSecurity-with-Outh

spring.security.oauth2.client.registration.github.client-id=Ov23liug5J9kXDNdpvyj

spring.security.oauth2.client.registration.github.client-secret=ed0811ff231289acfba63d75cd41189e81ede6ed
