spring.application.name=SpringSecurity-with-Outh

spring.security.oauth2.client.registration.github.client-id=Ov23liug5J9kXDNdpvyj

spring.security.oauth2.client.registration.github.client-secret=ed0811ff231289acfba63d75cd41189e81ede6ed

spring.datasource.url=jdbc:mysql://localhost:3306/25june
 
spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
